### ISSUE TITLE
Launcher not working

### ISSUE THREAD

**Issue by esbennn** [flathub/com.visualstudio.code.oss#49] opened 2019-10-18 07:00 UTC
Since updating VSCode a few days ago, the launcher does not work.
Clicking the launcher from Activities or from dash simply does nothing.
Running it with `flatpak run com.visualstudio.code.oss` works just fine though.
System details:
```
[playground@darkgreen ~] $ screenfetch
           /:-------------:\          playground@darkgreen
        :-------------------::        OS: Fedora 30 Thirty
      :-----------/shhOHbmp---:\      Kernel: x86_64 Linux 5.3.5-200.fc30.x86_64
    /-----------omMMMNNNMMD  ---:     Uptime: 3m
   :-----------sMMMMNMNMP.    ---:    Packages: 4326
  :-----------:MMMdP-------    ---\   Shell: bash 5.0.7
 ,------------:MMMd--------    ---:   Resolution: 3840x1080
 :------------:MMMd-------    .---:   DE: GNOME 
 :----    oNMMMMMMMMMNho     .----:   WM: GNOME Shell
 :--     .+shhhMMMmhhy++   .------/   WM Theme: 
 :-    -------:MMMd--------------:    GTK Theme: Adwaita [GTK2/3]
 :-   --------/MMMd-------------;     Icon Theme: Paper
 :-    ------/hMMMy------------:      Font: Cantarell 11
 :-- :dMNdhhdNMMNo------------;       CPU: Intel Core i5-4570 @ 4x 3.6GHz [27.8°C]
 :---:sdNMMMMNds:------------:        GPU: AMD VERDE (DRM 2.50.0, 5.3.5-200.fc30.x86_64, LLVM 8.0.0)
 :------:://:-------------::          RAM: 4150MiB / 15941MiB
 :---------------------://           
```
```
[playground@darkgreen ~] $ flatpak --version
Flatpak 1.4.3
```
```
[playground@darkgreen ~] $ flatpak info com.visualstudio.code.oss 

Visual Studio Code - OSS - Visual Studio Code. Code editing. Redefined.

           ID: com.visualstudio.code.oss
          Ref: app/com.visualstudio.code.oss/x86_64/stable
         Arch: x86_64
       Branch: stable
      Version: 1.39.1
      License: MIT
       Origin: flathub
   Collection: org.flathub.Stable
 Installation: system
    Installed: 235,6 MB
      Runtime: org.freedesktop.Sdk/x86_64/18.08
          Sdk: org.freedesktop.Sdk/x86_64/18.08

Active commit: d773779e6396f62fd6199b276ed260f615eaef5568e21484e2ef35bec7002aac
Latest commit: 42affc3f3cf04345432ed8b957345d08eeb2399bb8f4d5c6618c0b8a006be93d
       Parent: 78e762a5b0673c64057cb3879d01c4d3fb5d433b7a473bc5aefa45f7d1970a22
      Subject: Update com.visualstudio.code.oss.json (5eb89f83)
         Date: 2019-10-13 06:36:18 +0000
```

**Comment by amtlib-dot-dll** [comment] 2019-10-22 11:54
Duplicate of #48 which is resolved, please upgrade to latest version

**Closed by amtlib-dot-dll** 2019-10-22 11:54 UTC
Labels: duplicate
